### PR TITLE
Avoid "Missing serialize REPR function for REPR VMException (BOOTExce…

### PR DESCRIPTION
**Pull request by eiselekd**
…ption)"

``` (try require Terminal::ANSIColor) !=== Nil ```
results in ```Missing serialize REPR function for REPR VMException (BOOTException)``` , dont know howto fix it otherwise.

### CODE REVIEW

**Comment by eiselekd** [comment]
related to #12

**Comment by timo** [comment]
can you try what happens when you assign Nil to $! after the try?

**Comment by eiselekd** [comment]
How do you mean: original was:
`my $has-color = (try require Terminal::ANSIColor) !=== Nil;`
can you specify the new line to test?

**Comment by timo** [comment]
i'm sorry. it turns out i already wrote the patch to fix this almost a year ago and just forgot to push it. can you check if the latest version works fine without Terminal::ANSIColor?

**Comment by eiselekd** [comment]
Tested it and works. Thanks.

**Comment by eiselekd** [comment]
Is it possible that you also take a look at : https://github.com/edumentab/p6-moarvm-remote/issues/2 
and pull request https://github.com/edumentab/p6-moarvm-remote/pull/3 ?
as p6-app-moarvm-debug depends on it.

**Comment by eiselekd** [comment]
I'm not shure weather it is zef or not but via zef it is still failing.

**Pull request closed without merging**
